/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,css}'],
  theme: {
    extend: {
      colors: {
        paper:        'oklch(97% 0.01 75)',
        'paper-2':    'oklch(94% 0.01 75)',
        'paper-3':    'oklch(90% 0.01 75)',
        ink:          'oklch(15% 0.01 60)',
        'ink-2':      'oklch(40% 0.01 60)',
        rule:         'oklch(85% 0.01 60)',
        accent:       'oklch(55% 0.18 25)',
        'accent-ink': 'oklch(99% 0.00 0)',
        teal:         'oklch(62% 0.08 175)',
        'teal-ink':   'oklch(99% 0.00 0)',
        highlight:    'oklch(88% 0.14 85)',
        'highlight-ink': 'oklch(20% 0.05 60)',
        error:        'oklch(52% 0.20 25)',
        'error-ink':  'oklch(99% 0.00 0)',
      },
      fontFamily: {
        display: ['"Instrument Serif"', 'Georgia', 'serif'],
        body:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display':  ['clamp(2.5rem, 5vw + 1rem, 4rem)', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-s':['2rem', { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline': ['1.5rem', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg':  ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body':     ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':  ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label':    ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      spacing: {
        '3xs': '0.25rem',
        '2xs': '0.5rem',
        'xs':  '0.75rem',
        'sm':  '1rem',
        'md':  '1.5rem',
        'lg':  '2rem',
        'xl':  '3rem',
        '2xl': '4.5rem',
        'margin-mobile': '1.25rem',
        'margin-desktop': '2rem',
      },
      borderRadius: {
        sm:   '6px',
        DEFAULT: '8px',
        md:   '8px',
        lg:   '12px',
        xl:   '16px',
        pill: '999px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
